const { app, BrowserWindow, ipcMain, crashReporter, dialog } = require('electron');
const path = require('path');
const fs   = require('fs');
const os   = require('os');
const chokidar = require('chokidar');
const { detectArma3, detectArmaDocuments, findLatestRptLog } = require('./armaDetector');

// ─── Single instance lock ────────────────────────────────────────────────────
const gotTheLock = app.requestSingleInstanceLock();
if (!gotTheLock) {
  app.quit();
} else {
  app.on('second-instance', () => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    }
  });
}

// ─── Crash reporter ──────────────────────────────────────────────────────────
crashReporter.start({
  companyName: 'SPECTRE',
  productName: 'SPECTRE C2',
  submitURL: '',
  uploadToServer: false,
  compress: true,
});

// ─── Directory paths ─────────────────────────────────────────────────────────
const USER_DATA    = app.getPath('userData');
const BRIDGE_DIR   = path.join(USER_DATA, 'bridge');
const MISSIONS_DIR = path.join(USER_DATA, 'missions');
const INTEL_DIR    = path.join(USER_DATA, 'intel');
const CONFIG_PATH  = path.join(USER_DATA, 'config.json');

// ─── Auto-detect Arma 3 ─────────────────────────────────────────────────────
let _configData;
try { _configData = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8')); } catch (_) { _configData = {}; }

const ARMA_INSTALL = (_configData.arma_path && fs.existsSync(_configData.arma_path))
  ? _configData.arma_path
  : detectArma3();
const ARMA_DOCS    = detectArmaDocuments();
const ARMA_SPECTRE = path.join(ARMA_DOCS, 'SPECTRE');

// Persist detected path back to config if we found one and config didn't have it
if (ARMA_INSTALL && !_configData.arma_path) {
  try {
    let cfg = {};
    try { cfg = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8')); } catch (_) {}
    cfg.arma_path = ARMA_INSTALL;
    fs.writeFileSync(CONFIG_PATH, JSON.stringify(cfg, null, 2));
  } catch (_) {}
}

const DEBUG_LOG = path.join(USER_DATA, 'debug.log');
function dbg(msg) {
  const line = `[${new Date().toISOString()}] ${msg}\n`;
  try { fs.appendFileSync(DEBUG_LOG, line); } catch (_) {}
  console.log(line.trimEnd());
}

dbg('SPECTRE: App starting');
dbg('SPECTRE: Arma 3 install: ' + (ARMA_INSTALL || '(not found)'));
dbg('SPECTRE: Arma 3 documents: ' + ARMA_DOCS);
dbg('SPECTRE: Config path: ' + CONFIG_PATH);

// ─── Default config ──────────────────────────────────────────────────────────
const DEFAULT_CONFIG = {
  ai_provider:   'openrouter',
  api_keys:      [],
  model:         'qwen/qwen3-next-80b-a3b-instruct:free',
  fallback_model:'qwen/qwen3-next-80b-a3b-instruct:free',
  base_url:      'https://openrouter.ai/api/v1',
  mission_folder_path: '',
  arma_path:     '',
  auto_abort_threshold: {
    firepower_loss_pct: 50,
    crew_kia: 2
  }
};

// ─── Ensure directories exist ────────────────────────────────────────────────
[BRIDGE_DIR, MISSIONS_DIR, INTEL_DIR, ARMA_SPECTRE].forEach(d => {
  try { if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true }); } catch (_) {}
});
if (!fs.existsSync(CONFIG_PATH)) {
  fs.writeFileSync(CONFIG_PATH, JSON.stringify(DEFAULT_CONFIG, null, 2));
}

// ─── Command queue ───────────────────────────────────────────────────────────
let pendingCommands = [];

function buildSQFContent(commands) {
  if (commands.length === 0) return '// SPECTRE — no pending commands\n';

  const lines = [
    `// SPECTRE Command Batch — ${new Date().toISOString()}`,
    `// DO NOT EDIT — auto-generated by SPECTRE C2`,
  ];

  for (const cmd of commands) {
    const id   = cmd._id || Date.now();
    const type = (cmd.type     || '').replace(/[^A-Z0-9_]/g, '');
    const uid  = (cmd.unit_id  || 'ALL').replace(/["'\n\r]/g, '');

    switch (type) {
      case 'HOLD':
      case 'RTB':
      case 'HOLD_ALL':
      case 'RTB_ALL':
      case 'WEAPONS_FREE':
      case 'WEAPONS_SAFE':
      case 'FORM_UP':
      case 'DISPERSE':
        lines.push(`[${id}, "${type}", "${uid}"] call SPECTRE_fnc_execCmd;`);
        break;

      case 'EXECUTE_ORDER': {
        const wps = (cmd.waypoints || [])
          .filter(wp => wp && (wp.x !== undefined || wp.y !== undefined))
          .map(wp => `[${Math.round(wp.x || 0)},${Math.round(wp.y || 0)}]`)
          .join(',');
        const roe    = (cmd.engagement_rules || '').replace(/["'\n\r]/g, '').substring(0, 60);
        const action = (cmd.action           || '').replace(/["'\n\r]/g, '').substring(0, 100);
        lines.push(`[${id}, "EXECUTE_ORDER", "${uid}", [${wps}], "${roe}", "${action}"] call SPECTRE_fnc_execCmd;`);
        break;
      }

      case 'CUSTOM': {
        const instr = (cmd.instruction || '').replace(/["'\n\r]/g, '').substring(0, 100);
        lines.push(`[${id}, "CUSTOM", "${uid}", [], "", "${instr}"] call SPECTRE_fnc_execCmd;`);
        break;
      }

      default:
        lines.push(`// (skipped unknown command type: ${cmd.type})`);
    }
  }

  return lines.join('\n') + '\n';
}

function flushCommandsToMission() {
  if (pendingCommands.length === 0) return;

  let config;
  try { config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8')); }
  catch (_) { config = DEFAULT_CONFIG; }

  const missionFolder = config.mission_folder_path;
  if (!missionFolder || !fs.existsSync(missionFolder)) {
    console.warn('SPECTRE: mission_folder_path not set or does not exist. Commands dropped.');
    pendingCommands = [];
    return;
  }

  const content = buildSQFContent(pendingCommands);
  const outPath = path.join(missionFolder, 'spectre_to_arma.sqf');

  try {
    fs.writeFileSync(outPath, content, 'utf8');
    console.log(`SPECTRE: wrote ${pendingCommands.length} command(s) to ${outPath}`);
  } catch (e) {
    console.error('SPECTRE: failed to write command file:', e.message);
  }

  pendingCommands = [];
}

function queueCommand(cmd) {
  const id = Date.now() + Math.floor(Math.random() * 10000);
  pendingCommands.push({ ...cmd, _id: id });
  flushCommandsToMission();
}

// ─── Auto-install mod to Arma 3 ──────────────────────────────────────────────
function tryInstallMod() {
  if (!ARMA_INSTALL) return;

  const armaModDir = path.join(ARMA_INSTALL, '@SPECTRE');
  const bundledMod = path.join(__dirname, '..', 'mod');

  // Already installed?
  if (fs.existsSync(path.join(armaModDir, 'mod.cpp'))) {
    console.log('SPECTRE: mod already installed at', armaModDir);
    return;
  }

  // Bundled mod exists?
  if (!fs.existsSync(bundledMod)) {
    console.log('SPECTRE: no bundled mod found, skipping auto-install');
    return;
  }

  const result = dialog.showMessageBoxSync(mainWindow, {
    type: 'question',
    buttons: ['Install Mod', 'Skip'],
    defaultId: 0,
    title: 'SPECTRE C2 — Mod Installation',
    message: 'Install the SPECTRE mod to Arma 3?',
    detail: `Arma 3 detected at:\n${ARMA_INSTALL}\n\nThe mod will be installed to:\n${armaModDir}`,
  });

  if (result !== 0) return;

  try {
    copyDirRecursive(bundledMod, armaModDir);
    console.log('SPECTRE: mod installed to', armaModDir);
    dialog.showMessageBox(mainWindow, {
      type: 'info',
      title: 'SPECTRE C2',
      message: 'Mod installed successfully!',
      detail: 'You can now launch Arma 3 with the @SPECTRE mod enabled.',
    });
  } catch (e) {
    console.error('SPECTRE: mod install failed:', e.message);
    dialog.showMessageBox(mainWindow, {
      type: 'error',
      title: 'SPECTRE C2',
      message: 'Mod installation failed',
      detail: e.message,
    });
  }
}

// ─── Manual mod install (from Settings) ──────────────────────────────────────
ipcMain.handle('install-mod', async (_, modType) => {
  if (!ARMA_INSTALL) {
    return { success: false, error: 'Arma 3 path not set. Go to Settings and set the Arma 3 Installation Path first.' };
  }

  if (modType === 'spectre') {
    const armaModDir = path.join(ARMA_INSTALL, '@SPECTRE');
    const bundledMod = path.join(__dirname, '..', 'mod');

    if (!fs.existsSync(bundledMod)) {
      return { success: false, error: 'Bundled mod not found in app directory.' };
    }

    try {
      copyDirRecursive(bundledMod, armaModDir);
      console.log('SPECTRE: mod installed to', armaModDir);
      return { success: true, path: armaModDir };
    } catch (e) {
      return { success: false, error: e.message };
    }
  }

  if (modType === 'cba') {
    const cbaDir = path.join(ARMA_INSTALL, '@CBA_A3');
    if (fs.existsSync(path.join(cbaDir, 'mod.cpp'))) {
      return { success: true, path: cbaDir, message: 'CBA_A3 already installed.' };
    }

    // Download CBA_A3 from GitHub
    try {
      const https = require('https');

      // Get latest release
      console.log('SPECTRE: Fetching CBA_A3 latest release...');
      const releaseData = await new Promise((resolve, reject) => {
        https.get('https://api.github.com/repos/CBATeam/CBA_A3/releases/latest', { headers: { 'User-Agent': 'SPECTRE-C2' } }, (res) => {
          let data = '';
          res.on('data', chunk => data += chunk);
          res.on('end', () => {
            try { resolve(JSON.parse(data)); } catch (e) { reject(new Error('Failed to parse GitHub response')); }
          });
        }).on('error', reject);
      });

      // Find the .zip asset
      const asset = releaseData.assets?.find(a => a.name.endsWith('.zip'));
      if (!asset) return { success: false, error: 'Could not find CBA_A3 download in latest release.' };
      console.log('SPECTRE: Found CBA_A3 asset:', asset.name, 'size:', asset.size);

      // Download with redirect handling
      const downloadUrl = asset.browser_download_url;
      console.log('SPECTRE: Downloading from:', downloadUrl);

      const zipPath = path.join(ARMA_INSTALL, 'cba_a3_temp.zip');
      await new Promise((resolve, reject) => {
        const download = (url) => {
          https.get(url, { headers: { 'User-Agent': 'SPECTRE-C2' } }, (res) => {
            if (res.statusCode === 302 || res.statusCode === 301) {
              console.log('SPECTRE: Following redirect to:', res.headers.location);
              download(res.headers.location);
            } else if (res.statusCode === 200) {
              const file = fs.createWriteStream(zipPath);
              let downloaded = 0;
              res.on('data', (chunk) => {
                downloaded += chunk.length;
              });
              res.pipe(file);
              file.on('finish', () => {
                file.close();
                console.log('SPECTRE: Downloaded', downloaded, 'bytes');
                resolve();
              });
            } else {
              reject(new Error(`Download failed with status ${res.statusCode}`));
            }
          }).on('error', reject);
        };
        download(downloadUrl);
      });

      // Check file exists and has size
      const zipStat = fs.statSync(zipPath);
      console.log('SPECTRE: ZIP file size:', zipStat.size, 'bytes');
      if (zipStat.size < 1000) {
        fs.unlinkSync(zipPath);
        return { success: false, error: 'Downloaded file is too small - download may have failed.' };
      }

      // Extract using PowerShell
      console.log('SPECTRE: Extracting CBA_A3...');
      const { execSync } = require('child_process');
      fs.mkdirSync(cbaDir, { recursive: true });
      execSync(`powershell -Command "Expand-Archive -Path '${zipPath}' -DestinationPath '${cbaDir}' -Force"`, { stdio: 'ignore' });
      fs.unlinkSync(zipPath);

      // Fix nested folder: CBA_A3 zip extracts to @CBA_A3/@CBA_A3/, move contents up
      const nestedDir = path.join(cbaDir, '@CBA_A3');
      if (fs.existsSync(nestedDir)) {
        console.log('SPECTRE: Fixing nested folder structure...');
        const items = fs.readdirSync(nestedDir);
        for (const item of items) {
          const src = path.join(nestedDir, item);
          const dest = path.join(cbaDir, item);
          fs.renameSync(src, dest);
        }
        fs.rmdirSync(nestedDir);
      }

      // Verify installation
      if (!fs.existsSync(path.join(cbaDir, 'mod.cpp'))) {
        return { success: false, error: 'Extraction completed but mod.cpp not found. The zip format may have changed.' };
      }

      console.log('SPECTRE: CBA_A3 installed to', cbaDir);
      return { success: true, path: cbaDir };
    } catch (e) {
      console.error('SPECTRE: CBA_A3 install error:', e.message);
      return { success: false, error: `Failed to download CBA_A3: ${e.message}` };
    }
  }

  return { success: false, error: 'Unknown mod type.' };
});

ipcMain.handle('check-mod-status', async () => {
  const mods = {};
  if (ARMA_INSTALL) {
    mods.spectre = fs.existsSync(path.join(ARMA_INSTALL, '@SPECTRE', 'mod.cpp'));
    mods.cba = fs.existsSync(path.join(ARMA_INSTALL, '@CBA_A3', 'mod.cpp'));
  }
  return mods;
});

function copyDirRecursive(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

// ─── Window ──────────────────────────────────────────────────────────────────
let mainWindow;
let logFilePos = 0;
let currentLogPath = null;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1600, height: 1000,
    minWidth: 1280, minHeight: 800,
    backgroundColor: '#070b10',
    titleBarStyle: 'hidden',
    frame: false,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, 'preload.js')
    }
  });

  const isDev = process.env.NODE_ENV === 'development' ||
    !fs.existsSync(path.join(__dirname, '../build/index.html'));

  if (isDev) {
    mainWindow.loadURL('http://localhost:3000');
    if (process.env.DEVTOOLS) mainWindow.webContents.openDevTools({ mode: 'detach' });
  } else {
    mainWindow.loadFile(path.join(__dirname, '../build/index.html'));
  }

  mainWindow.on('closed', () => { mainWindow = null; });
}

// ─── Auto-update ─────────────────────────────────────────────────────────────
function setupAutoUpdate() {
  try {
    const { autoUpdater } = require('electron-updater');
    autoUpdater.autoDownload = true;
    autoUpdater.autoInstallOnAppQuit = true;

    autoUpdater.on('update-available', (info) => {
      console.log('SPECTRE: Update available:', info.version);
      sendToRenderer('update-available', info);
    });

    autoUpdater.on('update-downloaded', (info) => {
      console.log('SPECTRE: Update downloaded:', info.version);
      sendToRenderer('update-downloaded', info);
    });

    autoUpdater.on('error', (err) => {
      console.error('SPECTRE: Auto-update error:', err.message);
    });

    // Check for updates on startup (delay 10s to not block startup)
    setTimeout(() => {
      autoUpdater.checkForUpdates().catch(() => {});
    }, 10000);
  } catch (_) {
    // electron-updater not installed, skip
  }
}

// ─── App ready ───────────────────────────────────────────────────────────────
app.whenReady().then(() => {
  createWindow();
  startBridgeWatcher();
  setupAutoUpdate();
  tryInstallMod();
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

// ─── Bridge Watchers ─────────────────────────────────────────────────────────
function startBridgeWatcher() {
  // Legacy JSON bridge
  const jsonFile = path.join(ARMA_SPECTRE, 'arma_to_spectre.json');
  chokidar.watch(jsonFile, { persistent: true, usePolling: true, interval: 500 })
    .on('change', () => {
      try {
        const data = JSON.parse(fs.readFileSync(jsonFile, 'utf8'));
        sendToRenderer('arma-state-update', data);
      } catch (_) {}
    });

  // Tail Arma RPT log
  watchArmaLog();

  console.log('SPECTRE: bridge watching Arma log files');
}

function watchArmaLog() {
  // Find latest RPT log
  const logPath = findLatestRptLog(ARMA_DOCS);

  if (!logPath) {
    dbg('SPECTRE: no RPT log found, retrying in 5s...');
    setTimeout(watchArmaLog, 5000);
    return;
  }

  // If we switched to a new log file, reset position
  if (logPath !== currentLogPath) {
    currentLogPath = logPath;
    try { logFilePos = fs.statSync(logPath).size; } catch (_) { logFilePos = 0; }
    dbg('SPECTRE: tailing Arma log: ' + logPath + ' at offset ' + logFilePos);
  }

  // Use chokidar for file watching
  chokidar.watch(logPath, { persistent: true, usePolling: true, interval: 500 })
    .on('change', () => {
      try {
        const stat = fs.statSync(logPath);

        // Log rotated (file shrunk) — reset position
        if (stat.size < logFilePos) {
          logFilePos = 0;
        }

        if (stat.size === logFilePos) return;

        const fd  = fs.openSync(logPath, 'r');
        const len = stat.size - logFilePos;
        const buf = Buffer.alloc(len);
        fs.readSync(fd, buf, 0, len, logFilePos);
        fs.closeSync(fd);
        logFilePos = stat.size;

        const chunk = buf.toString('utf8');
        parseArmaLog(chunk);

        // Check for newer RPT files periodically
        checkForNewerLog();
      } catch (e) {
        console.error('SPECTRE: log read error:', e.message);
      }
    });

  // Fallback: polling timer in case chokidar misses changes
  setInterval(() => {
    try {
      const latestRpt = findLatestRptLog(ARMA_DOCS);
      if (latestRpt && latestRpt !== currentLogPath) {
        console.log('SPECTRE: new RPT detected by polling:', latestRpt);
        currentLogPath = latestRpt;
        try { logFilePos = fs.statSync(latestRpt).size; } catch (_) { logFilePos = 0; }
        // Watch the new file too
        chokidar.watch(latestRpt, { persistent: true, usePolling: true, interval: 500 })
          .on('change', () => {
            try {
              const stat = fs.statSync(latestRpt);
              if (stat.size < logFilePos) { logFilePos = 0; }
              if (stat.size === logFilePos) return;
              const fd  = fs.openSync(latestRpt, 'r');
              const len = stat.size - logFilePos;
              const buf = Buffer.alloc(len);
              fs.readSync(fd, buf, 0, len, logFilePos);
              fs.closeSync(fd);
              logFilePos = stat.size;
              parseArmaLog(buf.toString('utf8'));
              checkForNewerLog();
            } catch (e) {}
          });
      }

      // Also re-read current file in case chokidar missed
      if (currentLogPath && fs.existsSync(currentLogPath)) {
        const stat = fs.statSync(currentLogPath);
        if (stat.size > logFilePos) {
          const len = stat.size - logFilePos;
          const fd = fs.openSync(currentLogPath, 'r');
          const buf = Buffer.alloc(len);
          fs.readSync(fd, buf, 0, len, logFilePos);
          fs.closeSync(fd);
          logFilePos = stat.size;
          parseArmaLog(buf.toString('utf8'));
        }
      }
    } catch (_) {}
  }, 2000);
}

// Check if a newer RPT file has appeared (log rotation by Arma)
let lastLogCheck = 0;
function checkForNewerLog() {
  const now = Date.now();
  if (now - lastLogCheck < 30000) return; // Check every 30s max
  lastLogCheck = now;

  const newer = findLatestRptLog(ARMA_DOCS);
  if (newer && newer !== currentLogPath) {
    console.log('SPECTRE: newer RPT log detected, switching:', newer);
    currentLogPath = newer;
    try { logFilePos = fs.statSync(newer).size; } catch (_) { logFilePos = 0; }
  }
}

// Accumulator for multi-line state
let pendingState = { units: {}, contacts: {}, events: [], mapName: null, missionFolder: null, timestamp: 0 };

function parseArmaLog(chunk) {
  const lines = chunk.split('\n');
  let gotData = false;

  for (const line of lines) {
    // New per-line format: SPECTRE_META, SPECTRE_UNIT, SPECTRE_CONTACT, SPECTRE_EVENTS
    const metaMatch = line.match(/SPECTRE_META:(\{.+\})/);
    if (metaMatch) {
      try {
        const jsonStr = metaMatch[1].replace(/""/g, '"');
        const meta = JSON.parse(jsonStr);
        if (meta.map) pendingState.mapName = meta.map;
        if (meta.mf) pendingState.missionFolder = meta.mf;
        if (meta.ts) pendingState.timestamp = meta.ts;
        gotData = true;
      } catch (e) { dbg('SPECTRE: meta parse error: ' + e.message); }
      continue;
    }

    const unitMatch = line.match(/SPECTRE_UNIT:(\{.+\})/);
    if (unitMatch) {
      try {
        const jsonStr = unitMatch[1].replace(/""/g, '"');
        const raw = JSON.parse(jsonStr);
        const u = expandUnit(raw);
        pendingState.units[u.id] = u;
        gotData = true;
      } catch (e) { dbg('SPECTRE: unit parse error: ' + e.message); }
      continue;
    }

    const contactMatch = line.match(/SPECTRE_CONTACT:(\{.+\})/);
    if (contactMatch) {
      try {
        const jsonStr = contactMatch[1].replace(/""/g, '"');
        const raw = JSON.parse(jsonStr);
        pendingState.contacts[raw.id] = {
          id: raw.id,
          type: raw.type || raw.vtype || 'UNKNOWN',
          position: raw.position || raw.pos || { x: 0, y: 0, lat: 0, lng: 0 },
          state: raw.state || 'CONFIRMED',
          source: raw.source || 'VISUAL',
          confidence: raw.confidence || 'HIGH'
        };
        gotData = true;
      } catch (e) { dbg('SPECTRE: contact parse error: ' + e.message); }
      continue;
    }

    const eventsMatch = line.match(/SPECTRE_EVENTS:(\[.+\])/);
    if (eventsMatch) {
      try {
        const jsonStr = eventsMatch[1].replace(/""/g, '"');
        const evts = JSON.parse(jsonStr);
        pendingState.events = pendingState.events.concat(evts);
        gotData = true;
      } catch (e) { dbg('SPECTRE: events parse error: ' + e.message); }
      continue;
    }

    // Legacy format fallback: SPECTRE_STATE (single-line JSON)
    const stateMatch = line.match(/SPECTRE_STATE:(\{.+\})/);
    if (stateMatch) {
      try {
        const jsonStr = stateMatch[1].replace(/""/g, '"');
        const raw = JSON.parse(jsonStr);
        const data = expandLegacyState(raw);
        if (data.missionFolder) autoSetMissionFolder(data.missionFolder);
        sendToRenderer('arma-state-update', data);
        gotData = true;
      } catch (e) {
        dbg('SPECTRE: legacy parse error: ' + e.message);
      }
    }
  }

  // After processing all lines in this chunk, flush the accumulated state
  if (gotData && (Object.keys(pendingState.units).length > 0 || pendingState.mapName)) {
    const data = {
      missionFolder: pendingState.missionFolder || '',
      mapName: pendingState.mapName || '',
      timestamp: pendingState.timestamp,
      units: Object.values(pendingState.units),
      contacts: Object.values(pendingState.contacts),
      events: pendingState.events
    };
    dbg(`SPECTRE: FLUSH — units: ${data.units.length}, map: ${data.mapName}`);
    data.units.forEach(u => dbg(`  UNIT: id=${u.id}, pos=${JSON.stringify(u.position)}, hp=${u.health}`));

    if (data.missionFolder) autoSetMissionFolder(data.missionFolder);
    sendToRenderer('arma-state-update', data);

    // Reset accumulator (keep mapName and missionFolder for next chunk)
    pendingState.units = {};
    pendingState.contacts = {};
    pendingState.events = [];
  }
}

function expandUnit(raw) {
  return {
    id: raw.id,
    callsign: raw.callsign || raw.id,
    type: raw.type || (['MBT','IFV','APC','RECON','HELI','TRUCK','PLANE'].includes(raw.vtype) ? 'VEHICLE' : 'INFANTRY'),
    vehicle_type: raw.vehicle_type || raw.vtype || 'INFANTRY',
    position: raw.position || raw.pos || { x: 0, y: 0, lat: 0, lng: 0 },
    heading: raw.heading ?? raw.hdg ?? 0,
    health: raw.health ?? raw.hp ?? 100,
    fuel: raw.fuel ?? 100,
    ammo: raw.ammo ?? 100,
    status: raw.status || raw.st || 'UNKNOWN',
    current_order: raw.current_order || raw.order || ''
  };
}

function expandLegacyState(raw) {
  return {
    missionFolder: raw.missionFolder || '',
    mapName: raw.mapName || '',
    armaVersion: raw.armaVersion || '',
    timestamp: raw.timestamp || 0,
    units: (raw.units || []).map(expandUnit),
    contacts: (raw.contacts || []).map(c => ({
      id: c.id, type: c.type, position: c.position || c.pos || {},
      state: c.state || 'CONFIRMED', source: c.source || 'VISUAL', confidence: c.confidence || 'HIGH'
    })),
    events: raw.events || []
  };
}

// Auto-set mission folder from bridge's getMissionPath broadcast
let lastAutoSet = '';
function autoSetMissionFolder(missionPath) {
  if (!missionPath || missionPath === lastAutoSet) return;
  lastAutoSet = missionPath;

  // Normalize path
  let normalized = missionPath.replace(/\/$/, '').replace(/\//g, '\\');

  // If path is relative (no drive letter), resolve against Arma install dir
  if (normalized && !normalized.match(/^[A-Z]:\\/i) && ARMA_INSTALL) {
    normalized = path.join(ARMA_INSTALL, normalized);
  }

  if (!fs.existsSync(normalized)) {
    console.warn('SPECTRE: mission folder not found:', normalized);
    return;
  }

  let config;
  try { config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8')); }
  catch (_) { config = { ...DEFAULT_CONFIG }; }

  // Only update if different from current
  if (config.mission_folder_path !== normalized) {
    config.mission_folder_path = normalized;
    fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2));
    console.log('SPECTRE: auto-detected mission folder:', normalized);
    sendToRenderer('config-updated', config);
  }
}

function sendToRenderer(channel, data) {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send(channel, data);
  } else {
    dbg(`SPECTRE: IPC skipped (no window), channel: ${channel}`);
  }
}

// ─── Auto-detect Arma mission folders ────────────────────────────────────────
function getMissionFolders() {
  const scanRoots = [
    path.join(ARMA_DOCS, 'missions'),
    path.join(ARMA_DOCS, 'mpmissions'),
  ];

  const results = [];
  for (const root of scanRoots) {
    if (!fs.existsSync(root)) continue;
    try {
      const entries = fs.readdirSync(root, { withFileTypes: true });
      for (const e of entries) {
        if (!e.isDirectory()) continue;
        const full = path.join(root, e.name);
        const files = fs.readdirSync(full).map(f => f.toLowerCase());
        const looksLikeMission = files.some(f =>
          f === 'description.ext' || f === 'init.sqf' || f.endsWith('.sqf')
        );
        if (looksLikeMission) {
          results.push({ name: e.name, path: full });
        }
      }
    } catch (_) {}
  }

  results.sort((a, b) => {
    try {
      return fs.statSync(b.path).mtime - fs.statSync(a.path).mtime;
    } catch (_) { return 0; }
  });

  return results;
}

// ─── IPC Handlers ────────────────────────────────────────────────────────────

ipcMain.handle('send-command', async (_, command) => {
  try {
    queueCommand(command);
    return { success: true };
  } catch (e) {
    return { success: false, error: e.message };
  }
});

ipcMain.handle('get-config', async () => {
  try {
    const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
    if (config.api_key && !config.api_keys?.length) {
      config.api_keys = [config.api_key];
      delete config.api_key;
    }
    if (config.model === 'anthropic/claude-opus-4-5') config.model = DEFAULT_CONFIG.model;
    if (config.fallback_model === 'openai/gpt-4o' || config.fallback_model === 'openai/gpt-4o-mini') config.fallback_model = DEFAULT_CONFIG.fallback_model;
    if (!Array.isArray(config.api_keys)) config.api_keys = [];
    return config;
  }
  catch (_) { return { ...DEFAULT_CONFIG }; }
});

ipcMain.handle('save-config', async (_, config) => {
  let existing = {};
  try { existing = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8')); } catch (_) {}
  const merged = { ...existing, ...config };
  if (ARMA_INSTALL) merged.arma_path = ARMA_INSTALL;
  fs.writeFileSync(CONFIG_PATH, JSON.stringify(merged, null, 2));
  return { success: true };
});

ipcMain.handle('save-mission', async (_, missionData) => {
  const filename = `mission_${Date.now()}.json`;
  fs.writeFileSync(path.join(MISSIONS_DIR, filename), JSON.stringify(missionData, null, 2));
  return { success: true, filename };
});

ipcMain.handle('load-intel', async () => {
  const p = path.join(INTEL_DIR, 'intel_db.json');
  if (!fs.existsSync(p)) return { locations: [], patterns: [], terrain: [] };
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); }
  catch (_) { return { locations: [], patterns: [], terrain: [] }; }
});

ipcMain.handle('save-intel', async (_, intel) => {
  fs.writeFileSync(path.join(INTEL_DIR, 'intel_db.json'), JSON.stringify(intel, null, 2));
  return { success: true };
});

ipcMain.handle('get-mission-folders', async () => {
  return getMissionFolders();
});

ipcMain.handle('get-paths', async () => {
  let config;
  try { config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8')); } catch (_) { config = DEFAULT_CONFIG; }

  return {
    bridge_dir:           BRIDGE_DIR,
    arma_spectre_dir:     ARMA_SPECTRE,
    missions_dir:         MISSIONS_DIR,
    arma_install:         ARMA_INSTALL || '(not found)',
    mission_folder_path:  config.mission_folder_path || '(auto-detecting...)',
    spectre_to_arma:      config.mission_folder_path
      ? path.join(config.mission_folder_path, 'spectre_to_arma.sqf')
      : '(waiting for Arma connection)',
    arma_log_watched:     currentLogPath || '(not found — launch Arma first)'
  };
});

ipcMain.handle('get-arma-info', async () => {
  return {
    installPath: ARMA_INSTALL,
    documentsPath: ARMA_DOCS,
    detected: !!ARMA_INSTALL,
  };
});

let customArmaPath = null;

ipcMain.handle('set-arma-path', async (_, manualPath) => {
  if (!manualPath) {
    // Browse for folder
    const result = await dialog.showOpenDialog(mainWindow, {
      properties: ['openDirectory'],
      title: 'Select Arma 3 Installation Directory',
    });
    if (result.canceled || !result.filePaths[0]) return { success: false };
    manualPath = result.filePaths[0];
  }

  // Verify it looks like Arma 3
  const hasExe = fs.existsSync(path.join(manualPath, 'arma3_x64.exe')) ||
                 fs.existsSync(path.join(manualPath, 'arma3.exe'));
  if (!hasExe) {
    return { success: false, error: 'No arma3_x64.exe found in that directory.' };
  }

  customArmaPath = manualPath;
  ARMA_INSTALL = manualPath;
  console.log('SPECTRE: manual Arma 3 path set:', manualPath);
  return { success: true, path: manualPath };
});

// Window control IPC
ipcMain.on('minimize-window', () => mainWindow?.minimize());
ipcMain.on('maximize-window', () => mainWindow?.isMaximized() ? mainWindow.unmaximize() : mainWindow?.maximize());
ipcMain.on('close-window',    () => mainWindow?.close());
