const { app, BrowserWindow, ipcMain, crashReporter } = require('electron');
const path = require('path');
const fs   = require('fs');
const os   = require('os');
const chokidar = require('chokidar');
const { detectArma3, detectArmaDocuments, findLatestRptLog } = require('./armaDetector');

// ─── Single instance lock ────────────────────────────────────────────────────
const gotTheLock = app.requestSingleInstanceLock();
if (!gotTheLock) {
  app.quit();
} else {
  app.on('second-instance', () => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    }
  });
}

// ─── Crash reporter ──────────────────────────────────────────────────────────
crashReporter.start({
  companyName: 'SPECTRE',
  productName: 'SPECTRE C2',
  submitURL: '',
  uploadToServer: false,
  compress: true,
});

// ─── Directory paths ─────────────────────────────────────────────────────────
const USER_DATA    = app.getPath('userData');
const BRIDGE_DIR   = path.join(USER_DATA, 'bridge');
const MISSIONS_DIR = path.join(USER_DATA, 'missions');
const INTEL_DIR    = path.join(USER_DATA, 'intel');
const CONFIG_PATH  = path.join(USER_DATA, 'config.json');

// ─── Auto-detect Arma 3 ─────────────────────────────────────────────────────
const ARMA_INSTALL = detectArma3();
const ARMA_DOCS    = detectArmaDocuments();
const ARMA_SPECTRE = path.join(ARMA_DOCS, 'SPECTRE');

console.log('SPECTRE: Arma 3 install:', ARMA_INSTALL || '(not found)');
console.log('SPECTRE: Arma 3 documents:', ARMA_DOCS);

// ─── Default config ──────────────────────────────────────────────────────────
const DEFAULT_CONFIG = {
  ai_provider:   'openrouter',
  api_keys:      [],
  model:         'qwen/qwen3-next-80b-a3b-instruct:free',
  fallback_model:'qwen/qwen3-next-80b-a3b-instruct:free',
  base_url:      'https://openrouter.ai/api/v1',
  mission_folder_path: '',
  auto_abort_threshold: {
    firepower_loss_pct: 50,
    crew_kia: 2
  }
};

// ─── Ensure directories exist ────────────────────────────────────────────────
[BRIDGE_DIR, MISSIONS_DIR, INTEL_DIR, ARMA_SPECTRE].forEach(d => {
  try { if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true }); } catch (_) {}
});
if (!fs.existsSync(CONFIG_PATH)) {
  fs.writeFileSync(CONFIG_PATH, JSON.stringify(DEFAULT_CONFIG, null, 2));
}

// ─── Command queue ───────────────────────────────────────────────────────────
let pendingCommands = [];

function buildSQFContent(commands) {
  if (commands.length === 0) return '// SPECTRE — no pending commands\n';

  const lines = [
    `// SPECTRE Command Batch — ${new Date().toISOString()}`,
    `// DO NOT EDIT — auto-generated by SPECTRE C2`,
  ];

  for (const cmd of commands) {
    const id   = cmd._id || Date.now();
    const type = (cmd.type     || '').replace(/[^A-Z0-9_]/g, '');
    const uid  = (cmd.unit_id  || 'ALL').replace(/["'\n\r]/g, '');

    switch (type) {
      case 'HOLD':
      case 'RTB':
      case 'HOLD_ALL':
      case 'RTB_ALL':
      case 'WEAPONS_FREE':
      case 'WEAPONS_SAFE':
      case 'FORM_UP':
      case 'DISPERSE':
        lines.push(`[${id}, "${type}", "${uid}"] call SPECTRE_fnc_execCmd;`);
        break;

      case 'EXECUTE_ORDER': {
        const wps = (cmd.waypoints || [])
          .filter(wp => wp && (wp.x !== undefined || wp.y !== undefined))
          .map(wp => `[${Math.round(wp.x || 0)},${Math.round(wp.y || 0)}]`)
          .join(',');
        const roe    = (cmd.engagement_rules || '').replace(/["'\n\r]/g, '').substring(0, 60);
        const action = (cmd.action           || '').replace(/["'\n\r]/g, '').substring(0, 100);
        lines.push(`[${id}, "EXECUTE_ORDER", "${uid}", [${wps}], "${roe}", "${action}"] call SPECTRE_fnc_execCmd;`);
        break;
      }

      case 'CUSTOM': {
        const instr = (cmd.instruction || '').replace(/["'\n\r]/g, '').substring(0, 100);
        lines.push(`[${id}, "CUSTOM", "${uid}", [], "", "${instr}"] call SPECTRE_fnc_execCmd;`);
        break;
      }

      default:
        lines.push(`// (skipped unknown command type: ${cmd.type})`);
    }
  }

  return lines.join('\n') + '\n';
}

function flushCommandsToMission() {
  if (pendingCommands.length === 0) return;

  let config;
  try { config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8')); }
  catch (_) { config = DEFAULT_CONFIG; }

  const missionFolder = config.mission_folder_path;
  if (!missionFolder || !fs.existsSync(missionFolder)) {
    console.warn('SPECTRE: mission_folder_path not set or does not exist. Commands dropped.');
    pendingCommands = [];
    return;
  }

  const content = buildSQFContent(pendingCommands);
  const outPath = path.join(missionFolder, 'spectre_to_arma.sqf');

  try {
    fs.writeFileSync(outPath, content, 'utf8');
    console.log(`SPECTRE: wrote ${pendingCommands.length} command(s) to ${outPath}`);
  } catch (e) {
    console.error('SPECTRE: failed to write command file:', e.message);
  }

  pendingCommands = [];
}

function queueCommand(cmd) {
  const id = Date.now() + Math.floor(Math.random() * 10000);
  pendingCommands.push({ ...cmd, _id: id });
  flushCommandsToMission();
}

// ─── Window ──────────────────────────────────────────────────────────────────
let mainWindow;
let logFilePos = 0;
let currentLogPath = null;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1600, height: 1000,
    minWidth: 1280, minHeight: 800,
    backgroundColor: '#070b10',
    titleBarStyle: 'hidden',
    frame: false,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, 'preload.js')
    }
  });

  const isDev = process.env.NODE_ENV === 'development' ||
    !fs.existsSync(path.join(__dirname, '../build/index.html'));

  if (isDev) {
    mainWindow.loadURL('http://localhost:3000');
    if (process.env.DEVTOOLS) mainWindow.webContents.openDevTools({ mode: 'detach' });
  } else {
    mainWindow.loadFile(path.join(__dirname, '../build/index.html'));
  }

  mainWindow.on('closed', () => { mainWindow = null; });
}

// ─── Auto-update ─────────────────────────────────────────────────────────────
function setupAutoUpdate() {
  try {
    const { autoUpdater } = require('electron-updater');
    autoUpdater.autoDownload = true;
    autoUpdater.autoInstallOnAppQuit = true;

    autoUpdater.on('update-available', (info) => {
      console.log('SPECTRE: Update available:', info.version);
      sendToRenderer('update-available', info);
    });

    autoUpdater.on('update-downloaded', (info) => {
      console.log('SPECTRE: Update downloaded:', info.version);
      sendToRenderer('update-downloaded', info);
    });

    autoUpdater.on('error', (err) => {
      console.error('SPECTRE: Auto-update error:', err.message);
    });

    // Check for updates on startup (delay 10s to not block startup)
    setTimeout(() => {
      autoUpdater.checkForUpdates().catch(() => {});
    }, 10000);
  } catch (_) {
    // electron-updater not installed, skip
  }
}

// ─── App ready ───────────────────────────────────────────────────────────────
app.whenReady().then(() => {
  createWindow();
  startBridgeWatcher();
  setupAutoUpdate();
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

// ─── Bridge Watchers ─────────────────────────────────────────────────────────
function startBridgeWatcher() {
  // Legacy JSON bridge
  const jsonFile = path.join(ARMA_SPECTRE, 'arma_to_spectre.json');
  chokidar.watch(jsonFile, { persistent: true, usePolling: true, interval: 500 })
    .on('change', () => {
      try {
        const data = JSON.parse(fs.readFileSync(jsonFile, 'utf8'));
        sendToRenderer('arma-state-update', data);
      } catch (_) {}
    });

  // Tail Arma RPT log
  watchArmaLog();

  console.log('SPECTRE: bridge watching Arma log files');
}

function watchArmaLog() {
  // Find latest RPT log
  const logPath = findLatestRptLog(ARMA_DOCS);

  if (!logPath) {
    setTimeout(watchArmaLog, 5000);
    return;
  }

  // If we switched to a new log file, reset position
  if (logPath !== currentLogPath) {
    currentLogPath = logPath;
    try { logFilePos = fs.statSync(logPath).size; } catch (_) { logFilePos = 0; }
    console.log('SPECTRE: tailing Arma log:', logPath);
  }

  chokidar.watch(logPath, { persistent: true, usePolling: true, interval: 500 })
    .on('change', () => {
      try {
        const stat = fs.statSync(logPath);

        // Log rotated (file shrunk) — reset position
        if (stat.size < logFilePos) {
          logFilePos = 0;
        }

        if (stat.size === logFilePos) return;

        const fd  = fs.openSync(logPath, 'r');
        const len = stat.size - logFilePos;
        const buf = Buffer.alloc(len);
        fs.readSync(fd, buf, 0, len, logFilePos);
        fs.closeSync(fd);
        logFilePos = stat.size;

        parseArmaLog(buf.toString('utf8'));

        // Check for newer RPT files periodically
        checkForNewerLog();
      } catch (e) {
        console.error('SPECTRE: log read error:', e.message);
      }
    });
}

// Check if a newer RPT file has appeared (log rotation by Arma)
let lastLogCheck = 0;
function checkForNewerLog() {
  const now = Date.now();
  if (now - lastLogCheck < 30000) return; // Check every 30s max
  lastLogCheck = now;

  const newer = findLatestRptLog(ARMA_DOCS);
  if (newer && newer !== currentLogPath) {
    console.log('SPECTRE: newer RPT log detected, switching:', newer);
    currentLogPath = newer;
    try { logFilePos = fs.statSync(newer).size; } catch (_) { logFilePos = 0; }
  }
}

function parseArmaLog(chunk) {
  for (const line of chunk.split('\n')) {
    const stateMatch = line.match(/SPECTRE_STATE:(\{.+\})/);
    if (stateMatch) {
      try {
        const data = JSON.parse(stateMatch[1]);

        // Auto-detect mission folder from bridge broadcast
        if (data.missionFolder) {
          autoSetMissionFolder(data.missionFolder);
        }

        sendToRenderer('arma-state-update', data);
      } catch (_) {}
    }
    const eventMatch = line.match(/SPECTRE_EVENT:(\{.+\})/);
    if (eventMatch) {
      try { sendToRenderer('arma-event', JSON.parse(eventMatch[1])); } catch (_) {}
    }
  }
}

// Auto-set mission folder from bridge's getMissionPath broadcast
let lastAutoSet = '';
function autoSetMissionFolder(missionPath) {
  if (!missionPath || missionPath === lastAutoSet) return;
  lastAutoSet = missionPath;

  // Normalize path
  const normalized = missionPath.replace(/\/$/, '').replace(/\//g, '\\');
  if (!fs.existsSync(normalized)) return;

  let config;
  try { config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8')); }
  catch (_) { config = { ...DEFAULT_CONFIG }; }

  // Only update if different from current
  if (config.mission_folder_path !== normalized) {
    config.mission_folder_path = normalized;
    fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2));
    console.log('SPECTRE: auto-detected mission folder:', normalized);
    sendToRenderer('config-updated', config);
  }
}

function sendToRenderer(channel, data) {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send(channel, data);
  }
}

// ─── Auto-detect Arma mission folders ────────────────────────────────────────
function getMissionFolders() {
  const scanRoots = [
    path.join(ARMA_DOCS, 'missions'),
    path.join(ARMA_DOCS, 'mpmissions'),
  ];

  const results = [];
  for (const root of scanRoots) {
    if (!fs.existsSync(root)) continue;
    try {
      const entries = fs.readdirSync(root, { withFileTypes: true });
      for (const e of entries) {
        if (!e.isDirectory()) continue;
        const full = path.join(root, e.name);
        const files = fs.readdirSync(full).map(f => f.toLowerCase());
        const looksLikeMission = files.some(f =>
          f === 'description.ext' || f === 'init.sqf' || f.endsWith('.sqf')
        );
        if (looksLikeMission) {
          results.push({ name: e.name, path: full });
        }
      }
    } catch (_) {}
  }

  results.sort((a, b) => {
    try {
      return fs.statSync(b.path).mtime - fs.statSync(a.path).mtime;
    } catch (_) { return 0; }
  });

  return results;
}

// ─── IPC Handlers ────────────────────────────────────────────────────────────

ipcMain.handle('send-command', async (_, command) => {
  try {
    queueCommand(command);
    return { success: true };
  } catch (e) {
    return { success: false, error: e.message };
  }
});

ipcMain.handle('get-config', async () => {
  try {
    const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
    if (config.api_key && !config.api_keys?.length) {
      config.api_keys = [config.api_key];
      delete config.api_key;
    }
    if (config.model === 'anthropic/claude-opus-4-5') config.model = DEFAULT_CONFIG.model;
    if (config.fallback_model === 'openai/gpt-4o' || config.fallback_model === 'openai/gpt-4o-mini') config.fallback_model = DEFAULT_CONFIG.fallback_model;
    if (!Array.isArray(config.api_keys)) config.api_keys = [];
    return config;
  }
  catch (_) { return { ...DEFAULT_CONFIG }; }
});

ipcMain.handle('save-config', async (_, config) => {
  fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2));
  return { success: true };
});

ipcMain.handle('save-mission', async (_, missionData) => {
  const filename = `mission_${Date.now()}.json`;
  fs.writeFileSync(path.join(MISSIONS_DIR, filename), JSON.stringify(missionData, null, 2));
  return { success: true, filename };
});

ipcMain.handle('load-intel', async () => {
  const p = path.join(INTEL_DIR, 'intel_db.json');
  if (!fs.existsSync(p)) return { locations: [], patterns: [], terrain: [] };
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); }
  catch (_) { return { locations: [], patterns: [], terrain: [] }; }
});

ipcMain.handle('save-intel', async (_, intel) => {
  fs.writeFileSync(path.join(INTEL_DIR, 'intel_db.json'), JSON.stringify(intel, null, 2));
  return { success: true };
});

ipcMain.handle('get-mission-folders', async () => {
  return getMissionFolders();
});

ipcMain.handle('get-paths', async () => {
  let config;
  try { config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8')); } catch (_) { config = DEFAULT_CONFIG; }

  return {
    bridge_dir:           BRIDGE_DIR,
    arma_spectre_dir:     ARMA_SPECTRE,
    missions_dir:         MISSIONS_DIR,
    arma_install:         ARMA_INSTALL || '(not found)',
    mission_folder_path:  config.mission_folder_path || '(auto-detecting...)',
    spectre_to_arma:      config.mission_folder_path
      ? path.join(config.mission_folder_path, 'spectre_to_arma.sqf')
      : '(waiting for Arma connection)',
    arma_log_watched:     currentLogPath || '(not found — launch Arma first)'
  };
});

ipcMain.handle('get-arma-info', async () => {
  return {
    installPath: ARMA_INSTALL,
    documentsPath: ARMA_DOCS,
    detected: !!ARMA_INSTALL,
  };
});

// Window control IPC
ipcMain.on('minimize-window', () => mainWindow?.minimize());
ipcMain.on('maximize-window', () => mainWindow?.isMaximized() ? mainWindow.unmaximize() : mainWindow?.maximize());
ipcMain.on('close-window',    () => mainWindow?.close());
